/* eslint-disable */
// Stub — regenerated by `npx convex dev`
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.api = void 0;
exports.internal = void 0;
const server_1 = require("convex/server");
const api = (0, server_1.anyApi)();
exports.api = api;
const internal = (0, server_1.anyApi)();
exports.internal = internal;
