/* eslint-disable */
// Stub types for Convex server functions — regenerated by `npx convex dev`
import type { GenericQueryCtx, GenericMutationCtx, GenericActionCtx, DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema";

type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: any;
export declare const mutation: any;
export declare const action: any;
export declare const internalQuery: any;
export declare const internalMutation: any;
export declare const internalAction: any;
export declare const httpAction: any;
